#!/usr/bin/env python3

import actionlib
import math
import rospy
import tf2_ros
import tf2_geometry_msgs
import tf.transformations
import uuid

from axis_msgs.msg import Ptz
from geometry_msgs.msg import TransformStamped
from ptz_action_server_msgs.msg import PtzAction, PtzFeedback, PtzGoal, PtzResult
from ptz_action_server_msgs.msg import PtzRelToAction, PtzRelToFeedback, PtzRelToGoal, PtzRelToResult
from ptz_action_server_msgs.msg import PtzState
from sensor_msgs.msg import JointState
from threading import Lock, Thread

from math import pi
from math import degrees as rad2deg
from math import radians as deg2rad

def state_callback(data, node):
    node.state_callback(data)

def linear_rescale(x, old_min, old_max, new_min, new_max):
    return (x-old_min) / (old_max - old_min) * (new_max - new_min) + new_min

def clamp(x, min, max, metavar):
    if x < min:
        rospy.logwarn(f'Requested {metavar}={x} is too small. Clamping to {min}')
        return min
    elif x > max:
        rospy.logwarn(f'Requested {metavar}={x} is too large. Clamping to {max}')
        return max
    else:
        return x

class AxisPtzControlNode:
    """Provides a PTZ.action compatible interface for sending pan-tilt-zoom positions to the axis_camera driver
    """

    ## How long before we consider the last message sent on the status topic to be stale?
    STATE_TIMEOUT = rospy.Duration(10)

    def __init__(self):
        self.cmd_ns = rospy.get_param('~cmd_ns', '/axis/cmd')
        if self.cmd_ns[0] != '/':
            self.cmd_ns = f"/{self.cmd_ns}"
        self.cmd_pos_topic = f'{self.cmd_ns}/position'
        self.cmd_vel_topic = f'{self.cmd_ns}/velocity'
        self.status_topic = rospy.get_param('~status_topic', '/axis/state/position')
        self.act_ns = rospy.get_param('~act_ns', '/axis')
        self.invert_tilt = rospy.get_param('~invert_tilt', False)
        self.invert_pan = rospy.get_param('~invert_pan', False)

        self.min_pan = rospy.get_param("~min_pan", deg2rad(-170))
        self.max_pan = rospy.get_param("~max_pan", deg2rad(170))
        self.min_tilt = rospy.get_param("~min_tilt", 0)
        self.max_tilt = rospy.get_param("~max_tilt", deg2rad(90))
        self.min_hw_zoom = rospy.get_param("~min_zoom", 1)
        self.max_hw_zoom = rospy.get_param("~max_zoom", 9999)

        self.camera_base_link = rospy.get_param("~camera_base_link", "base_link")

        self.publish_joint_states = rospy.get_param("~publish_joint_states", True)
        self.pan_joint = rospy.get_param("~pan_joint", "pan_joint")
        self.tilt_joint = rospy.get_param("~tilt_joint", "tilt_joint")

        self.min_logical_zoom = rospy.get_param("~min_logical_zoom", 1)
        self.max_logical_zoom = rospy.get_param("~max_logical_zoom", 24)

        # allow 1 degree of error when tracking the position feedback
        # this is a little coarse, but the camera isn't a high-precision piece of kit anyway
        self.position_tolerance = deg2rad(1.0)

        # allow some tolerance in the zoom. This is a big range
        self.zoom_tolerance = 10.0

        self.goal_pan = 0.0
        self.goal_tilt = 0.0
        self.goal_zoom = 1.0

        # the camera's current state as reported by the underlying driver
        # initially None so we don't accidentally overwrite e.g. focus or brightness
        self.last_axis_state = None

        # The current logical PTZ state
        self.ptz_state = PtzState()
        self.ptz_state.pan = 0
        self.ptz_state.tilt = 0
        self.ptz_state.zoom = 1

        # is the camera currently moving?
        self.is_moving = False
        self.is_moving_lock = Lock()

        self.ptz_abs_srv = actionlib.SimpleActionServer(f'{self.act_ns}/move_ptz/position_abs', PtzAction, self.ptz_abs_actionHandler, False)
        self.ptz_rel_srv = actionlib.SimpleActionServer(f'{self.act_ns}/move_ptz/position_rel', PtzAction, self.ptz_rel_actionHandler, False)
        self.vel_srv = actionlib.SimpleActionServer(f'{self.act_ns}/move_ptz/velocity', PtzAction, self.vel_actionHandler, False)
        self.tf_ptz_abs_srv = actionlib.SimpleActionServer(f'{self.act_ns}/move_ptz/position_abs_tf', PtzRelTo, self.tf_ptz_abs_actionHandler, False)

        self.last_state_at = rospy.Time.now()
        self.last_command_at = rospy.Time.now()

        self.tf_broadcaster = tf2_ros.StaticTransformBroadcaster()
        self.camera_vector_frame = f"camera_vector_frame_{str(uuid.uuid1()).replace('-', '_')}"

    def start(self):
        """Starts the subscribers, publishers, and service handlers
        """
        self.cmd_pos_pub = rospy.Publisher(self.cmd_pos_topic, Ptz, queue_size=1)
        self.cmd_vel_pub = rospy.Publisher(self.cmd_vel_topic, Ptz, queue_size=1)
        self.status_sub = rospy.Subscriber(self.status_topic, Ptz, self.state_callback)
        self.status_pub = rospy.Publisher(f'{self.act_ns}/ptz_state', PtzState, queue_size=1)

        if self.publish_joint_states:
            self.joint_state_pub = rospy.Publisher("/joint_states", JointState, queue_size=1)
            self.js_thread = Thread(target=self.joint_state_pub_thread)
            self.js_thread.start()

        self.ptz_abs_srv.start()
        self.ptz_rel_srv.start()
        self.vel_srv.start()
        self.tf_ptz_abs_srv.start()

    def state_callback(self, data):
        """Monitors the position of the camera to determine if the pan and tilt joints have reached their
        goal positions yet

        Also saves the current state to self.last_axis_state

        @param data  The Ptz.msg information received on the topic
        """
        pan = data.pan
        tilt = data.tilt
        zoom = linear_rescale(data.zoom, self.min_hw_zoom, self.max_hw_zoom, self.min_logical_zoom, self.max_logical_zoom)

        # invert pan & tilt if necessary
        if self.invert_tilt:
            tilt = -tilt
        if self.invert_pan:
            pan = -pan

        if self.is_moving:
            if self.ptz_state.mode == PtzState.MODE_POSITION:
                pan_remaining = abs(self.goal_pan - pan)
                tilt_remaining = abs(self.goal_tilt - tilt)
                zoom_remaining = abs(self.goal_zoom - zoom)

                # check if we've reached the goal
                if pan_remaining <= self.position_tolerance and \
                   tilt_remaining <= self.position_tolerance and \
                   zoom_remaining <= self.zoom_tolerance:
                    rospy.loginfo("PTZ reached goal!")
                    self.is_moving = False
            elif self.ptz_state.mode == PtzState.MODE_VELOCITY:
                dpan = self.last_axis_state.pan - data.pan
                dtilt = self.last_axis_state.tilt - data.tilt
                dzoom = self.last_axis_state.zoom - data.zoom

                if dpan == 0 and dtilt == 0 and dzoom == 0:
                    rospy.loginfo("PTZ reached end-of-travel!")
                    self.is_moving = False

        self.last_axis_state = data
        self.last_state_at = rospy.Time.now()

        # publish the current PTZ state
        self.ptz_state.pan = pan
        self.ptz_state.tilt = tilt
        self.ptz_state.zoom = zoom
        self.status_pub.publish(self.ptz_state)

    def joint_state_pub_thread(self):
        js = JointState()

        rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            js.header.stamp = rospy.Time.now()
            js.name = [self.pan_joint, self.tilt_joint]
            js.position = [self.ptz_state.pan, self.ptz_state.tilt]
            js.velocity = [0, 0]
            js.effort = [0, 0]
            self.joint_state_pub.publish(js)
            rate.sleep()

    def ptz_abs_actionHandler(self, ptz_req):
        """Handles PTZ.action requests to set absolute pan/tilt/zoom positions

        Converts the PTZ goal into an Axis.msg we write to the axis_camera driver
        and then wait until the feedback topic reports that the PTU has finished moving

        @param ptz_req  The PtzGoal object to process
        """
        if self.last_axis_state == None:
            # We have never contacted the camera; block until we hear _something_
            rospy.logwarn('Still waiting for initial state from the camera. Cannot move yet')
            ptz_resp = PtzResult()
            ptz_resp.success = False
            self.ptz_abs_srv.set_aborted(ptz_resp, 'Still waiting for initial state from the camera. Cannot move yet')

        elif rospy.Time.now() - self.last_state_at > self.STATE_TIMEOUT:
            # We haven't heard from the camera in a while; block until the camera updates its status again
            rospy.logwarn("Status of Axis camera is stale. Waiting for the camera to come back online")
            ptz_resp = PtzResult()
            ptz_resp.success = False
            self.ptz_abs_srv.set_aborted(ptz_resp, "Status of Axis camera is stale; waiting for camera to publish its state again")

        else:
            if self.ptz_state.mode == PtzState.MODE_VELOCITY:
                self.vel_srv.set_aborted("Asserting position control")

            # The camera is alive and ready to move
            self.goal_pan = clamp(ptz_req.pan, self.min_pan, self.max_pan, 'pan')
            self.goal_tilt = clamp(ptz_req.tilt, self.min_tilt, self.max_tilt, 'tilt')
            self.goal_zoom = clamp(ptz_req.zoom, self.min_logical_zoom, self.max_logical_zoom, 'zoom')

            # send the command to the camera
            self.is_moving = True
            cmd = Ptz()
            cmd.pan = self.goal_pan
            cmd.tilt = self.goal_tilt
            cmd.zoom = self.goal_zoom
            self.cmd_pos_pub.publish(cmd)
            self.last_command_at = rospy.Time.now()
            self.ptz_state.mode = PtzState.MODE_POSITION

            # sleep until joint_states reports that the pan and tilt joints have reached the desired position OR
            # have stopped moving
            rate = rospy.Rate(2)
            timed_out = False
            while self.is_moving and not self.ptz_abs_srv.is_preempt_requested() and not timed_out:
                feedback = PtzFeedback()
                feedback.zoom_remaining = self.goal_zoom - self.ptz_state.zoom
                feedback.pan_remaining = self.goal_pan - self.ptz_state.pan
                feedback.tilt_remaining = self.goal_tilt - self.ptz_state.tilt
                self.ptz_abs_srv.publish_feedback(feedback)

                if rospy.Time.now() - self.last_state_at > self.STATE_TIMEOUT:
                    timed_out = True
                else:
                    rospy.logdebug(f"PTZ is still moving ({feedback.pan_remaining}, {feedback.tilt_remaining}, {feedback.zoom_remaining}) to go")
                    rate.sleep()

            if self.ptz_abs_srv.is_preempt_requested():
                rospy.logwarn("PTZ action preempted")
                self.is_moving = False
                self.ptz_abs_srv.set_preempted()
            elif timed_out:
                rospy.logwarn("Timed out waiting for axis camera state")
                self.is_moving = False
                ptz_resp = PtzResult()
                ptz_resp.success = False
                self.ptz_state.mode = PtzState.MODE_IDLE
                self.ptz_abs_srv.set_aborted(ptz_resp, "Timed out waiting for axis camera state; did the camera go offline?")
            else:
                rospy.logdebug("PTZ action completed successfully")
                ptz_resp = PtzResult()
                ptz_resp.success = True
                self.ptz_state.mode = PtzState.MODE_IDLE
                self.ptz_abs_srv.set_succeeded(ptz_resp)

    def ptz_rel_actionHandler(self, ptz_req):
        """Handler for moving the camera to a relative pan/tilt/zoom from current

        Converts the relative pan/tilt/zoom to absolute positions and uses the position_abs action
        """
        abs_goal = PtzGoal(self.ptz_state.pan + ptz_req.pan,
                           self.ptz_state.tilt + ptz_req.tilt,
                           self.ptz_state.zoom + ptz_req.zoom
        )

        ptz_client = actionlib.SimpleActionClient("move_ptz/position_abs", PtzAction)
        ptz_client.wait_for_server()

        def done_cb(state, result):
            if state == actionlib.GoalStatus.SUCCEEDED:
                self.ptz_rel_srv.set_succeeded(result)
            elif state == actionlib.GoalStatus.PREEMPTED:
                self.ptz_rel_srv.set_preempted()
            else:
                self.ptz_rel_srv.set_aborted(result)

        def feedback_cb(fb):
            self.ptz_rel_srv.publish_feedback(fb)

        ptz_client.send_goal(abs_goal,
            feedback_cb = feedback_cb,
            done_cb = done_cb
        )
        ptz_client.wait_for_result()

    def vel_actionHandler(self, ptz_req):
        """Handles PTZ.action requests for velocity control

        Converts the PTZ goal into an Axis.msg we write to the axis_camera driver
        and then wait until the feedback topic reports that the PTU has finished moving

        @param ptz_req  The PtzGoal object to process
        """
        if self.last_axis_state == None:
            # We have never contacted the camera; block until we hear _something_
            rospy.logwarn('Still waiting for initial state from the camera. Cannot move yet')
            ptz_resp = PtzResult()
            ptz_resp.success = False
            self.vel_srv.set_aborted(ptz_resp, 'Still waiting for initial state from the camera. Cannot move yet')
        elif rospy.Time.now() - self.last_state_at > self.STATE_TIMEOUT:
            # We haven't heard from the camera in a while; block until the camera updates its status again
            rospy.logwarn("Status of Axis camera is stale. Waiting for the camera to come back online")
            ptz_resp = PtzResult()
            ptz_resp.success = False
            self.vel_srv.set_aborted(ptz_resp, "Status of Axis camera is stale; waiting for camera to publish its state again")
        elif self.ptz_state.mode == PtzState.MODE_POSITION:
            # We're processiung a position command; it must finish first
            rospy.logwarn("Camera is moving under position control. Wait for that action to finish before using velocityu control")
            ptz_resp = PtzResult()
            ptz_resp.success = False
            self.vel_srv.set_aborted(ptz_resp, "Camera is moving under position control")
        elif self.ptz_state.mode == PtzState.MODE_VELOCITY and ptz_req.pan == 0 and ptz_req.tilt == 0 and ptz_req.zoom == 0:
            rospy.loginfo("Stopping camera")
            self.vel_srv.set_preempted()
        else:
            # The camera is alive and ready to move
            cmd = Ptz()
            cmd.pan = ptz_req.pan
            cmd.tilt = ptz_req.tilt
            cmd.zoom = ptz_req.zoom
            self.cmd_vel_pub.publish(cmd)
            if cmd.pan != 0 or cmd.tilt != 0 or cmd.zoom != 0:
                self.is_moving = True
                self.ptz_state.mode = PtzState.MODE_VELOCITY

                rate = rospy.Rate(2)
                timed_out = False
                while self.is_moving and not self.vel_srv.is_preempt_requested() and not timed_out:
                    feedback = PtzFeedback()
                    feedback.zoom_remaining = math.copysign(1, ptz_req.zoom)
                    feedback.pan_remaining = math.copysign(1, ptz_req.pan)
                    feedback.tilt_remaining = math.copysign(1, ptz_req.tilt)
                    self.vel_srv.publish_feedback(feedback)

                    if rospy.Time.now() - self.last_state_at > self.STATE_TIMEOUT:
                        timed_out = True
                    else:
                        rospy.logdebug(f"PTZ is still moving ({feedback.pan_remaining}, {feedback.tilt_remaining}, {feedback.zoom_remaining}) to go")
                        rate.sleep()

                if self.vel_srv.is_preempt_requested():
                    rospy.logwarn("Velocity action preempted")
                    self.is_moving = False
                    self.vel_srv.set_preempted()
                elif timed_out:
                    rospy.logwarn("Timed out waiting for axis camera state")
                    self.is_moving = False
                    ptz_resp = PtzResult()
                    ptz_resp.success = False
                    self.vel_state = PtzState.MODE_IDLE
                    self.vel_srv.set_aborted(ptz_resp, "Timed out waiting for axis camera state; did the camera go offline?")
                else:
                    rospy.logdebug("Velocity action completed successfully")
                    ptz_resp = PtzResult()
                    ptz_resp.success = True
                    self.ptz_state.mode = PtzState.MODE_IDLE
                    self.vel_srv.set_succeeded(ptz_resp)
            else:
                rospy.logdebug("Velocity action completed successfully")
                ptz_resp = PtzResult()
                ptz_resp.success = True
                self.is_moving = False
                self.ptz_state.mode = PtzState.MODE_IDLE
                self.vel_srv.set_succeeded(ptz_resp)

    def tf_ptz_abs_actionHandler(self, ptz_req):
        """Handler for a TF-aware absolute PTZ action

        We calculate the TF between the camera's base link & the link provided in the request, and then use
        the normal absolute PTZ action internally to move the camera to the corresponding position
        """
        # calculate the initial absolute goal as if there is no TF to apply
        abs_goal = PtzGoal(ptz_req.pan,
                           ptz_req.tilt,
                           ptz_req.zoom
        )

        if ptz_req.frame_id:
            try:
                # add a temporary frame to represent the desired camera vector
                camera_vector_q = tf.transformations.quaternion_from_euler(0, -ptz_req.tilt, ptz_req.pan)
                static_tf = TransformStamped()
                static_tf.header.stamp = rospy.Time.now()
                static_tf.header.frame_id = ptz_req.frame_id
                static_tf.child_frame_id = self.camera_vector_frame
                static_tf.transform.rotation.x = camera_vector_q[0]
                static_tf.transform.rotation.y = camera_vector_q[1]
                static_tf.transform.rotation.z = camera_vector_q[2]
                static_tf.transform.rotation.w = camera_vector_q[3]
                self.tf_broadcaster.sendTransform(static_tf)

                # The the RPY transformation between the camera base link & the reference frame
                tf_buffer = tf2_ros.Buffer(rospy.Duration(100.0))
                tf_listener = tf2_ros.TransformListener(tf_buffer)
                tf_stamped = tf_buffer.lookup_transform(self.camera_base_link, self.camera_vector_frame, rospy.Time(0), rospy.Duration(5.0))
                q = tf_stamped.transform.rotation
                (roll, pitch, yaw) = tf.transformations.euler_from_quaternion([q.x, q.y, q.z, q.w])

                # yaw & pitch are right-handed, but pan & tilt are left-handed, so invert them
                abs_goal.pan = -yaw
                abs_goal.tilt = -pitch

                # clamp the adjusted pan to lie within [-pi, pi]
                while abs_goal.pan < -math.pi:
                    abs_goal.pan += math.pi
                while abs_goal.pan > math.pi:
                    abs_goal.pan -= math.pi

                # clamp the adjusted tilt to lie within [-pi/2, pi/2]
                while abs_goal.tilt < -math.pi/2:
                    abs_goal.tilt += math.pi
                while abs_goal.tilt > math.pi/2:
                    abs_goal.tilt -= math.pi

        ptz_client = actionlib.SimpleActionClient("move_ptz/position_abs", PtzAction)
        ptz_client.wait_for_server()

        def done_cb(state, result):
            tf_result = PtzRelToResult(result.success)
            if state == actionlib.GoalStatus.SUCCEEDED:
                self.tf_ptz_abs_srv.set_succeeded(tf_result)
            elif state == actionlib.GoalStatus.PREEMPTED:
                self.tf_ptz_abs_srv.set_preempted()
            else:
                self.tf_ptz_abs_srv.set_aborted(tf_result)

        def feedback_cb(fb):
            tf_fb = PtzRelToFeedback(fb.pan_remaining, fb.tilt_remaining, fb.zoom_remaining)
            self.tf_ptz_abs_srv.publish_feedback(tf_fb)

        ptz_client.send_goal(abs_goal,
            feedback_cb = feedback_cb,
            done_cb = done_cb
        )
        ptz_client.wait_for_result()


def main():
    rospy.init_node('axis_ptz_action_server_node', anonymous=True)
    node = AxisPtzControlNode()
    node.start()
    rospy.spin()

if __name__=='__main__':
    main()
