#!/usr/bin/env python3

import rospy
import actionlib

from axis_camera.msg import Axis
from ptz_action_server_msgs.msg import PtzAction, PtzFeedback, PtzActionGoal, PtzResult
from ptz_action_server_msgs.msg import PtzPosition
from sensor_msgs.msg import JointState
from threading import Thread

from math import pi
from math import degrees as rad2deg
from math import radians as deg2rad

def state_callback(data, node):
    node.state_callback(data)

def linear_rescale(x, old_min, old_max, new_min, new_max):
    return (x-old_min) / (old_max - old_min) * (new_max - new_min) + new_min

def clamp(x, min, max, metavar):
    if x < min:
        rospy.logwarn(f'Requested {metavar}={x} is too small. Clamping to {min}')
        return min
    elif x > max:
        rospy.logwarn(f'Requested {metavar}={x} is too large. Clamping to {max}')
        return max
    else:
        return x

## Provides a PTZ.action compatible interface for sending pan-tilt-zoom positions to the axis_camera driver
class AxisPtzControlNode:
    ## How long before we consider the Axis.msg sent on the status topic to be stale?
    STATE_TIMEOUT = rospy.Duration(10)

    def __init__(self):
        self.cmd_topic = rospy.get_param('~cmd_topic', '/axis/cmd')
        self.status_topic = rospy.get_param('~status_topic', '/axis/state')
        self.act_ns = rospy.get_param('~act_ns', '/axis')
        self.invert_tilt = rospy.get_param('~invert_tilt', False)
        self.invert_pan = rospy.get_param('~invert_pan', False)

        self.min_pan = rospy.get_param("~min_pan", deg2rad(-170))
        self.max_pan = rospy.get_param("~max_pan", deg2rad(170))
        self.min_tilt = rospy.get_param("~min_tilt", 0)
        self.max_tilt = rospy.get_param("~max_tilt", deg2rad(90))
        self.min_hw_zoom = rospy.get_param("~min_zoom", 1)
        self.max_hw_zoom = rospy.get_param("~max_zoom", 9999)

        self.publish_joint_states = rospy.get_param("~publish_joint_states", True)
        self.pan_joint = rospy.get_param("~pan_joint", "pan_joint")
        self.tilt_joint = rospy.get_param("~tilt_joint", "tilt_joint")

        self.min_logical_zoom = rospy.get_param("~min_logical_zoom", 1)
        self.max_logical_zoom = rospy.get_param("~max_logical_zoom", 24)

        # allow 1 degree of error when tracking the position feedback
        # this is a little coarse, but the camera isn't a high-precision piece of kit anyway
        self.position_tolerance = deg2rad(1.0)

        # allow some tolerance in the zoom. This is a big range
        self.zoom_tolerance = 10.0

        self.goal_pan = 0.0
        self.goal_tilt = 0.0
        self.goal_zoom = 1.0

        # the camera's current state as reported by the underlying driver
        # initially None so we don't accidentally overwrite e.g. focus or brightness
        self.last_axis_state = None

        # The current logical PTZ state
        self.ptz_state = PtzPosition(0, 0, 1)

        # is the camera currently moving?
        self.is_moving = False

        self.ptz_srv = actionlib.SimpleActionServer(f'{self.act_ns}/move_ptz', PtzAction, self.ptz_actionHandler, False)

        self.last_state_at = rospy.Time.now()

        self.last_command_at = rospy.Time.now()


    ## Starts the subscribers, publishers, and service handlers
    def start(self):
        self.cmd_pub = rospy.Publisher(self.cmd_topic, Axis, queue_size=1)
        self.status_sub = rospy.Subscriber(self.status_topic, Axis, state_callback, self)
        self.status_pub = rospy.Publisher(f'{self.act_ns}/ptz_state', PtzPosition, queue_size=1)

        if self.publish_joint_states:
            self.joint_state_pub = rospy.Publisher("/joint_states", JointState, queue_size=1)
            self.js_thread = Thread(target=self.joint_state_pub_thread)
            self.js_thread.start()

        self.ptz_srv.start()


    ## Monitors /axis/state to determine if the pan and tilt joints have reached their goal positions yet
    #  Also saves the current state to self.last_axis_state
    #
    # \param data  The Axis.msg information received on the topic
    def state_callback(self, data):
        pan = deg2rad(data.pan)
        tilt = deg2rad(data.tilt)
        zoom = linear_rescale(data.zoom, self.min_hw_zoom, self.max_hw_zoom, self.min_logical_zoom, self.max_logical_zoom)

        # by default the underlying Axis driver uses + as right, but we use
        # + as left
        if not self.invert_pan:
            pan = -pan

        # invert the tilt if necessary
        if self.invert_tilt:
            tilt = -tilt

        dpan = abs(pan - self.goal_pan)
        dtilt = abs(tilt - self.goal_tilt)
        dzoom = abs(zoom - self.goal_zoom)

        if self.is_moving:
            # check if we've reached the goal
            if dpan <= self.position_tolerance and dtilt <= self.position_tolerance and dzoom <= self.zoom_tolerance:
                rospy.loginfo("PTZ reached goal!")
                self.is_moving = False
            elif self.last_axis_state.pan == data.pan and \
                 self.last_axis_state.tilt == data.tilt and \
                 self.last_axis_state.zoom == data.zoom and \
                 (rospy.Time.now() - self.last_command_at) > rospy.Duration(5):
                # check that we're actually moving towards the goal
                # if we aren't, re-send the command
                rospy.logwarn("Axis camera doesn't appear to be moving; re-sending last command")
                self.command_axis()

        self.last_axis_state = data
        self.last_state_at = rospy.Time.now()

        # publish the current PTZ state
        self.ptz_state.pan = pan
        self.ptz_state.tilt = tilt
        self.ptz_state.zoom = zoom
        self.status_pub.publish(self.ptz_state)

    def joint_state_pub_thread(self):
        js = JointState()

        rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            js.header.stamp = rospy.Time.now()
            js.name = [self.pan_joint, self.tilt_joint]
            js.position = [self.ptz_state.pan, self.ptz_state.tilt]
            js.velocity = [0, 0]
            js.effort = [0, 0]
            self.joint_state_pub.publish(js)
            rate.sleep()


    ## Handles PTZ.action requests
    #  Converts the PTZ goal into an Axis.msg we write to the axis_camera driver
    #  and then wait until the feedback topic reports that the PTU has finished moving
    #
    #  \param ptz_req  The PtzGoal object to process
    def ptz_actionHandler(self, ptz_req):
        if self.last_axis_state == None:
            # We have never contacted the camera; block until we hear _something_
            rospy.logwarn('Still waiting for initial state from the camera. Cannot move yet')
            ptz_resp = PtzResult()
            ptz_resp.success = False
            self.ptz_srv.set_aborted(ptz_resp, 'Still waiting for initial state from the camera. Cannot move yet')

        elif rospy.Time.now() - self.last_state_at > self.STATE_TIMEOUT:
            # We haven't heard from the camera in a while; block until the camera updates its status again
            rospy.logwarn("Status of Axis camera is stale. Waiting for the camera to come back online")
            ptz_resp = PtzResult()
            ptz_resp.success = False
            self.ptz_srv.set_aborted(ptz_resp, "Status of Axis camera is stale; waiting for camera to publish its state again")

        else:
            # The camera is alive and ready to move
            self.goal_pan = clamp(ptz_req.pan, self.min_pan, self.max_pan, 'pan')
            self.goal_tilt = clamp(ptz_req.tilt, self.min_tilt, self.max_tilt, 'tilt')
            self.goal_zoom = clamp(ptz_req.zoom, self.min_logical_zoom, self.max_logical_zoom, 'zoom')

            # send the command to the camera
            self.is_moving = True
            self.command_axis()

            # sleep until joint_states reports that the pan and tilt joints have reached the desired position OR
            # have stopped moving
            rate = rospy.Rate(2)
            timed_out = False
            while self.is_moving and not self.ptz_srv.is_preempt_requested() and not timed_out:
                feedback = PtzFeedback()
                feedback.zoom_remaining = self.goal_zoom - self.ptz_state.zoom
                feedback.pan_remaining = self.goal_pan - deg2rad(self.ptz_state.pan)
                feedback.tilt_remaining = self.goal_tilt - deg2rad(self.ptz_state.tilt)
                self.ptz_srv.publish_feedback(feedback)

                if rospy.Time.now() - self.last_state_at > self.STATE_TIMEOUT:
                    timed_out = True
                else:
                    rospy.logdebug(f"PTZ is still moving ({feedback.pan_remaining}, {feedback.tilt_remaining}, {feedback.zoom_remaining}) to go")
                    rate.sleep()

            if self.ptz_srv.is_preempt_requested():
                rospy.logwarn("PTZ action preempted")
                self.is_moving = False
                self.ptz_srv.set_preempted()
            elif timed_out:
                rospy.logwarn("Timed out waiting for axis camera state")
                self.is_moving = False
                self.ptz_srv.success = False
                self.ptz_srv.set_aborted(ptz_resp, "Timed out waiting for axis camera state; did the camera go offline?")
            else:
                rospy.logdebug("PTZ action completed successfully")
                ptz_resp = PtzResult()
                ptz_resp.success = True
                self.ptz_srv.set_succeeded(ptz_resp)


    ## Create the Axis.msg and send it to the camera hardware
    def command_axis(self):
        cmd = self.ptz_to_axis()
        self.cmd_pub.publish(cmd)
        self.last_command_at = rospy.Time.now()


    ## Convert the PtzResult to an Axis message we can write back to the driver
    #
    # \param  ptz_req   The PtzResult received from the service handler
    # \return an Axis object corresponding to the requested PTZ position
    def ptz_to_axis(self):
        axis = Axis()

        pan = rad2deg(self.goal_pan)
        tilt = rad2deg(self.goal_tilt)
        zoom = linear_rescale(self.goal_zoom, self.min_logical_zoom, self.max_logical_zoom, self.min_hw_zoom, self.max_hw_zoom)

        # by default the underlying Axis driver uses + as right, but we use
        # + as left
        if not self.invert_pan:
            pan = -pan

        # invert the tilt if necessary
        if self.invert_tilt:
            tilt = -tilt

        # set the PTZ values
        axis.pan = pan
        axis.tilt = tilt
        axis.zoom = zoom

        # copy the other camera settings from the current state
        axis.autofocus = self.last_axis_state.autofocus
        axis.autoiris = self.last_axis_state.autoiris
        axis.brightness = self.last_axis_state.brightness
        axis.focus = self.last_axis_state.focus
        axis.iris = self.last_axis_state.iris

        return axis


def main():
    rospy.init_node('axis_ptz_action_server_node', anonymous=True)
    node = AxisPtzControlNode()
    node.start()
    rospy.spin()

if __name__=='__main__':
    main()
