# Limits for the PTZ camera to ensure commands don't send it out of range
# These limits are for the Infiniti Optics Proton PRT

# Zoom level; this camera supports 1-24x zoom (approximately)
min_zoom: 1
max_zoom: 24

# This camera supports full-360 motion
min_pan: -3.141592653589793
max_pan: 3.141592653589793

# -26 degrees to 88 degrees
min_tilt: -0.4537856055185257
max_tilt: 1.53588974175501

# Camera-imposed limits on the actual zoom
hw_min_zoom: 0
hw_max_zoom: 16383

# Optionally invert the pan/tilt angles
# By default the Proton PTZ uses positive = clockwise pan, so the pan controls are inverted
invert_pan: true
invert_tilt: false
