# Defaults for common Axis dome cameras
# -170 to 170 pan
# 0 to 90 tilt
# 1-24x zoom (expressed as 1-9999 in the REST API)
min_pan: $(optenv AXIS_PTZ_MIN_PAN -2.9670597283903604)
max_pan: $(optenv AXIS_PTZ_MAX_PAN 2.9670597283903604)
min_tilt: $(optenv AXIS_PTZ_MIN_TILT 0.0)
max_tilt: $(optenv AXIS_PTZ_MAX_TILT 1.5707963267948966)
min_zoom: $(optenv AXIS_PTZ_MIN_ZOOM 1)
max_zoom: $(optenv AXIS_PTZ_MAX_ZOOM 9999)
min_logical_zoom: $(optenv AXIS_PTZ_MIN_LOGICAL_ZOOM 1)
max_logical_zoom: $(optenv AXIS_PTZ_MAX_LOGICAL_ZOOM 24)
