# Defaults for common Axis dome cameras mounted upside-down
# The Axis camera hardware detects the direction of gravity and automatically reverses the tilt direction
# -170 to 170 pan
# -90 to 0 tilt
# 1-24x zoom (expressed as 1-9999 in the REST API)
min_pan: -2.9670597283903604
max_pan: 2.9670597283903604
min_tilt: -1.5707963267948966
max_tilt: 0.0
min_zoom: 1
max_zoom: 9999
min_logical_zoom: 1
max_logical_zoom: 24
